version: "3.6"
services:
  frontend:
    image: ghcr.io/it-cheat-sheet/itcheatsheet-front-end:latest
    container_name: frontend
    ports:
       - "3001:3001"
networks:
    default:
        external:
            name: it-cheatsheet-network
