version: "3.6"
services:
  frontend:
    build: .
    container_name: frontend
    ports:
       - "80:80"
    secrets: 
     - source: deploy_key 
       target: ssh_key
      
networks:
    default:
        external:
            name: it-cheat-sheet-network
