name: Front-end

on:
  push:
    branches:  
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v2

      
    - name: Login to Github registry ghcr
      uses: docker/login-action@v1
      with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.ITCHEATSHEET_TOKEN }}
         
         
    - name: Build image and push Dockerfile
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        context: .
        push: true
        tags: ghcr.io/it-cheat-sheet/itcheatsheet-front-end:dev
   
    - name: Publish compose file
      uses: appleboy/scp-action@master
      with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.PRIVATE_KEY }}
         port: ${{ secrets.PORT }}
         source: ./docker-compose.dev.yml
         target: ./frontend
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
           docker-compose -f frontend/docker-compose.dev.yml down 
           docker pull ghcr.io/it-cheat-sheet/itcheatsheet-front-end:dev
           docker-compose -f frontend/docker-compose.dev.yml up -d 
